#!/bin/bash
if [ ! -d ".git" ]; then
    echo "We have detected that you have downloaded aimdroid-master.zip from the GitHub website. This is the WRONG way to download Aimdroid. Please download Aimdroid with the command 'git clone --recursive https://github.com/arzka/Aimdroid.git'"
    exit
else
	git pull
	git submodule update --recursive --remote
	git pull --recurse-submodules
	./build
fi
